### ISSUE TITLE
Unable to build: `-Werror` flags block the building of some dependencies

### ISSUE THREAD

**Issue by YannMagnin** [Jguer/yay#1523]
### Affected Version
__os__: ArchLinux version 5.12.8-arch1-1 #1 SMP PREEMPT Fri, 28 May 2021 15:10:20 +0000 x86_64 GNU/Linux (`uname -a`)
__go__: 1.16.4 linux/amd64 (`go version`)
__gcc__: 11.1.0 (`gcc --version`)
__pacman__: v6.0.0 - libalpm v13.0.0 (`pacman --version`)

### Describe the bug
After an update of `pacman`, `yay` has started to throw me this error: `yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory`. I wanted to reinstall `yay`, so that it will possibly find the `libalpm.so.12` again. But, when I try to build the package using `makepkg -si`, have got some log errors:

```txt
go build -trimpath -mod=readonly -modcacherw -tags six -ldflags '-X "main.yayVersion=10.2.2.r5.g059ca9d" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: downloading github.com/Jguer/go-alpm/v2 v2.0.5
go: downloading github.com/Morganamilo/go-pacmanconf v0.0.0-20210502114700-cff030e927a5
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
go: downloading github.com/leonelquinteros/gotext v1.4.0
go: downloading github.com/mikkeloscar/aur v0.0.0-20200113170522-1cb4e2949656
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/term v0.0.0-20210503060354-a79de5458b56
go: downloading github.com/stretchr/testify v1.7.0
go: downloading golang.org/x/sys v0.0.0-20210507161434-a76c4d0a0096
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go: downloading github.com/davecgh/go-spew v1.1.1
# runtime/cgo
gcc_fatalf.c: In function ‘fatalf’:
gcc_fatalf.c:17:9: error: implicit declaration of function ‘fprintf’ [-Werror=implicit-function-declaration]
   17 |         fprintf(stderr, "runtime/cgo: ");
      |         ^~~~~~~
gcc_fatalf.c:11:1: note: include ‘<stdio.h>’ or provide a declaration of ‘fprintf’
   10 | #include "libcgo.h"
  +++ |+#include <stdio.h>
   11 |
gcc_fatalf.c:17:9: error: incompatible implicit declaration of built-in function ‘fprintf’ [-Werror=builtin-declaration-mismatch]
   17 |         fprintf(stderr, "runtime/cgo: ");
      |         ^~~~~~~
gcc_fatalf.c:17:9: note: include ‘<stdio.h>’ or provide a declaration of ‘fprintf’
gcc_fatalf.c:19:9: error: implicit declaration of function ‘vfprintf’ [-Werror=implicit-function-declaration]
   19 |         vfprintf(stderr, format, ap);
      |         ^~~~~~~~
gcc_fatalf.c:19:9: note: include ‘<stdio.h>’ or provide a declaration of ‘vfprintf’
gcc_fatalf.c:22:9: error: implicit declaration of function ‘abort’ [-Werror=implicit-function-declaration]
   22 |         abort();
      |         ^~~~~
gcc_fatalf.c:11:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘abort’
   10 | #include "libcgo.h"
  +++ |+#include <stdlib.h>
   11 |
gcc_fatalf.c:22:9: error: incompatible implicit declaration of built-in function ‘abort’ [-Werror=builtin-declaration-mismatch]
   22 |         abort();
      |         ^~~~~
gcc_fatalf.c:22:9: note: include ‘<stdlib.h>’ or provide a declaration of ‘abort’
cc1: all warnings being treated as errors
make: *** [Makefile:112: yay] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
It's obvious that a genius have set the `-Werror` flag somewhere in some dependencies, but I'm not able to find it and remove it. Any idea to remove or force disable this cursed flag?

**Comment by Jguer** [comment]
@Paquity have you checked if there's no `-Werror` in your environment's CFLAGS (`echo $CFLAGS`) or in your `/etc/makepkg.conf` CFLAGS (apart from `-Werror=format-security`)

**Comment by YannMagnin** [comment]
`echo $CFLAGS` give me nothing and I don't have any extra `-Werror` in `/etc/makepkg.conf` :/

**Comment by saurabhs** [comment]
getting the same error after upgrading pacman to 6.0

os: Linux arch 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux (uname -a)
go: 1.15.4 linux/amd64 (go version)
gcc: 11.1.0 (gcc --version)
pacman: v6.0.0 - libalpm v13.0.0 (pacman --version)

**Comment by saurabhs** [comment]
yay seemed to working for me after I installed another AUR helper (paru) and ran paru -Syu
